on: [ push ]
name: Build
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runtime: [ "hello-world:latest", "laravel:8.0-octane", "laravel:8.1-octane" ]
    name: "bpkg.io/${{ matrix.runtime }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: bpkg.io
          username: k3s
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push bpkg.io/${{ matrix.runtime }}
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./runtimes/${{ matrix.runtime }}/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: true
          tags: |
            bpkg.io/${{ matrix.runtime }}
      - name: Build and push bpkg.io/${{ matrix.runtime }}-develop
        if: github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./runtimes/${{ matrix.runtime }}/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: true
          tags: |
            bpkg.io/${{ matrix.runtime }}-develop
